# Introduction

Increasing globalization of 
commerce, finance, production, and services
has fostered rapid global movement of people, animals, plants, 
food, and feed [@morse2001factors]. With the transportation
of people and goods comes the widespread dispersion of pathogens 
that cause infectious diseases and
the vectors that may spread them. Outbreaks that 
begin in the most remote parts of the world can now
spread swiftly to urban centers and to countries far 
away with dangerous, global consequences [@ex1995communicable]. 
For instance, population mobility across borders played a critical
role in the spread of Ebola in West Africa during the 
2013-2016 Ebola epidemic [@ebfactors].
A more recent example is the 2016 Yellow Fever outbreak in 
Angola. Infected travellers from Angola reached China,
representing the first ever reported cases of Yellow fever in Asia
[@wasserman2016yellow].

Early detection of infectious disease outbreaks through passive or
active collection of surveillance data can help public 
health officials initiate interventions such as 
removing contaminated food sources, isolating affected 
individuals or launching vaccination campaigns. However, 
any data collection method involves trade-offs between
speed, accuracy and costs. Data collected through
conventional surveillance such as through public health infrastructure,
are generally reliable but are resource intensive and are 
therefore typically available for upstream
analysis with an (understandable) delay.

The rapid growth of the internet has fostered a
corresponding increase in tools for internet based 
disease detection that lie at the other end of the spectrum.
Digital disease surveillance consists of monitoring 
online information sources to collate relevant 
information about diseases. The sources of information 
could be formal such as advisories posted by a ministry of 
health, or informal such as blogs or tweets. Digital 
surveillance makes data collection less expensive 
and time consuming but the acquired data are 
often less reliable than those collected through 
ground surveillance. Thus, digital 
surveillance tools can play a significant role 
in the rapid recognition of public health emergencies
[@grein2000rumors], [@anema2014digital].


The Program for Monitoring Emerging Diseases 
(ProMED, www.promedmail.org) was 
one of the first entrants in the field of digital 
disease detection. ProMED was created in 1994 as a surveillance
network to provide early warning of familiar as well as emerging 
infections [@morse2012public]. ProMED collates information from 
various sources that include
media reports, official reports, local observers, and a network
of clinicians throughout the world. The reports generated through
bottom-up surveillance are reviewed by a team of subject matter
experts before being posted to ProMED network. ProMED now provides 
free email 
based reports on outbreaks to over 70,000 subscribers in at 
least 185 countries. 

HealthMap (www.healthmap.org) is another widely used 
tool for disease outbreak monitoring. 
In addition to ProMED alerts, HealthMap utilises online news 
aggregators, eyewitness reports and other formal and informal
sources of information and allows for visualisation of alerts 
on a map [@freifeld2008healthmap]. 

Some other examples of digital disease detection tools include 
MediSys (http://medisys.newsbrief.eu/), H5N1 Google Earth mashup
(www.nature.com/avianflu/google-earth), and Emerging Infections 
Network (http://ein.idsociety.org). These tools 
provide a unique opportunity to rapidly 
detect new outbreaks and follow their evolution in near 
real-time. 

Collating timely data, while critical, is only the first 
step in the disease surveillance process. Compiling the data, 
conducting analysis, and generating reports that are 
easily understood and actionable are equally important. 
For instance, the 
spread of Zika to the Americas was reported 
in March 2014 by one of the subject matter experts at the 
ProMED [@promedzika], 
well before the
epidemic surfaced in South America in February 2015.
However, lacking an easy to use and openly accessible tool 
to quantify and visualize the risk associated with this report, 
it did not have any 
significant impact on public health resource allocation and 
decision making.
While there has been a
growing interest in using various internet data streams for 
epidemiological investigations [@generous2014global], 
[@milinovich2015role] and 
in using data from digital surveillance 
tools [@chowell2016elucidating], 
there is as yet a dearth of a
framework that can automatically combine such data with other 
streams of information analyse them in a statistically robust manner, 
and produce actionable reports, particularly in real time 
during an outbreak where such analyses would be most useful.


In this study, we propose a new statistical framework
to estimate and visualize risks posed by
outbreak events using digital surveillance data. 
Our approach relies on a relatively simple statistical
framework that integrates multiple data streams to
predict the future incidence trajectory, and 
quantify spatial heterogeneity in the risk of disease spread. 
In this paper, we present the model implemented in this system and as
a case study, we report the analysis of  ProMED and HealthMap data
for the 2013-16 West African Ebola epidemic. 
To assess the robustness of the digital surveillance data, 
we also applied the framework to the data 
collated by the World Health Organisation (WHO) and made available at 
the end of the epidemic. We present a comparison of the near real-time
ProMED/HealthMap data with the retrospective WHO data and the results of 
the spatiotemporal analysis carried out on these three data sources.

Our analysis based solely on epidemic data 
available through ProMED/HealthMap provides a 
realistic appraisal of their strengths and 
weaknesses, especially if used in near real-time 
forecasting.



