# Material and methods

## Processing ProMED/HealthMap data feed

We used a set of curated ProMED and HealthMap records on the human 
cases of Ebola in West Africa. 
The dates in the feeds ranged from March 2014 to October 2016.
The data set recorded the cumulative number of suspected/confirmed
cases and suspected/confirmed deaths by country at various dates
in this period. We derived the country specific daily and 
weekly incidence time series from these data after the 
following data cleaning and pre-processing:

+ We first extracted the total case
counts as a sum of suspected and confirmed cases (ProMED and HealthMap
data did not record probable cases). 

+ Each unique record 
in ProMED/HealthMap data is associated with a unique alert id.  Where
multiple records were associated with the same alert id, we merged
them by assigning the median of the case numbers to the record. 

+ In some instances, cumulative case count was inconsistent in that it
failed to be monotonically increasing. We identified consecutive dates
( $t_k$ and $t_{k + 1}$ where the cumulative case count was not
increasing. If removing either $t_k$ or $t_{k + 1}$ made the
cumulative case count increasing, we adopted this option. If however
removing either both or none of them resulted in a increasing series,
we removed both $t_k$ and $t_{k + 1}$. These rules were applied
iteratively until the cumulative case count was consistent.

+ Finally, cumulative incidence on days with no records was
filled in using log-linear interpolation. 

An example of the pre-processing of ProMED feed is presented in the 
supplementary text (`r si_fig_nums("pm_preprocessing")`).

## Data collated by WHO

We used the incidence data collated by the WHO during the West 
African Ebola epidemic made available by [@garske20160308], 
referred to as the ``WHO data'' in the interest of brevity. 
The cleaned version of the WHO data consisted of cases reported
between December 2013 and October 2015 in the three most affected
countries - Guinea, Sierra Leone and Liberia. The location of
residence of cases was geo-coded to the second administrative level. 
We aggregated the WHO data to national level to match the spatial
resolution of ProMED and HealthMap that were only available at the 
country level.

## Demographic Data

We used LandScan\textsuperscript{TM} 2015 dataset grid [@landscan] for 
population estimates and centroids for all countries on African mainland.

## Statistical model

Our model relies on a well-established statistical framework 
that assumes the daily incidence, $I_t$ , can be approximated with a
Poisson process following the renewal equation
[@fraser2007estimating]:

\[
  I_{t} \sim 
  Pois
  \left( 
    R_t \sum_{s = 1}^{t}{I_{t - s}\omega_s}
  \right).
\]

Here $R_t$ is the reproduction number at time $t$ (the average 
number of secondary cases per infected individual) and $\omega$
is the distribution of the serial interval (the time between onset of 
symptoms in a case and their infector).

We extend this model to incorporate the spatial spread of the
outbreak between  $n$ different locations.
The number of incident cases at a location $j$ at time $t$ is
given by the equation
\begin{align}
  I_{j}^{t} \sim 
  Pois\left( 
  \sum_{i = 1}^{n} 
  {\left( p_{i \rightarrow j}
  R_{i}^{t} \sum_{s = 1}^{t}{I_{i}^{t - s} \omega_{s}}
  \right)} 
  \right),
  (\#eq:likelihood)
\end{align}

where $R_{i}^{t}$ is the reproduction number at location $i$ at time
$t$ and $p_{i \rightarrow j}$ is the probability of a case moving from
location $i$ to location $j$ while they are infectious. $R_{i}^{t}$ is
affected by a number of factors e.g., the intrinsic
transmissibility of a pathogen or the health care capacity at location
$i$ (which could influence for example the capacity to isolate cases). 
The model could be easily extended to explicitly incorporate the
dependence of the reproduction number on such factors. 

The probability of moving between locations is derived from the
relative flow of populations between locations.
This latter quantity can be estimated using a population flow
model; here we used a gravity model [@grosche2007175], [@zipf1946p]. 
Under a gravity model, the flow of individuals from area $i$ to area $j$,
$\phi_{i \rightarrow j}$, is proportional to the product of the
populations of the two locations, $N_i$ and $N_j$ and inversely
proportional to the distance between them $d_{i, j}$, with all quantities
raised to some power:
\[
  \phi_{i \rightarrow j} =  \frac{N_i^{\alpha}N_j^{\beta}}{d_{i, j}^{\gamma}}.
\]

Here, we fixed $\alpha$ = $\beta$ = 1. The exponent $\gamma$, which modulates 
the effect of distance on the flow of
populations, was estimated. A large value of $\gamma$ indicates that the
distances travelled by populations tend to be short.

The relative risk of spread at a location $j$ from a location $i$
is thus proportional to the population flow into location $j$ from location $i$.

\[
  r_{i \rightarrow j}^{spread} = \frac{\phi_{i \rightarrow
  j}}{\sum_{x}{\phi_{i \rightarrow
  x}}}.
\]

The probability of movement from location $i$ to location $j$ is 
then given by
\[ p_{i \rightarrow j} = (1 - p_{stay}) r_{i \rightarrow j}^{spread},\]

where $p_{stay}$ is the probability that a case remains in 
a location $i$ throughout their infectious period. $p_{stay}$ is
assumed to be the same across all locations.


<!-- \subsection{Statistical inference of model parameters} -->

The parameters of the full model are: 

1.  $R_{i}^{t}$, the reproduction number at time $t$ in location $i$,
2.  $p_{stay}$, the probability of staying in a location, and 
3.  $\gamma$, the exponent of the distance in the gravity model. 


We used a Bayesian approach, and sampled from the joint posterior
distribution of all parameters using Markov Chain Monte Carlo
(MCMC). The likelihood of the
incidence at time $t$ in location $j$ given past incidence across all 
locations and model parameters is:

\begin{equation}
P \left( 
I_{j}^{t} \mid p_{stay}, \gamma, \omega, 
{\langle R_{i}^{t} \rangle}_{\{i = 1, 2, \dots n\}}, 
 {\langle I_{i}^{0} \rangle}_{\{i = 1, 2, \dots n\}}, \hdots {\langle I_{i}^{t} \rangle}_{\{i = 1, 2, \dots n\}} \right) 
 =  e^{-\lambda_{j}^{t}} \frac{(I_{j}^{t})^{\lambda_{j}^{t}}}{\lambda_{j}^{t} !},
\end{equation}

where $\lambda_{j}^{t}$ is given by

\begin{equation}
\lambda_{j}^{t} = \sum_{i = 1}^n{\left(p_{i \rightarrow j}R_{i}^{t} \sum_{s
        = 1}^T{I_{i}^{T - s} \omega_{s}} \right)},
(\#eq:lambdajt)		
\end{equation}
where $T$ is the duration of the outbreak so far.

Thus the likelihood of the parameters is proportional to

\[\mathcal{L} = P \left({\langle I_{j}^{t} \rangle}_{j = 1, 2 \dots n}
 \mid p_{stay}, \gamma, {\lanlge R_{j}^{t} \rangle}_{j = 1, 2 \dots n}\right) = 
 \prod_{t = 1}^{t}{e^{-\lambda_{i, t}} 
 \frac{I_{i}^{t}^{\lambda_{i}^{t}}}{\lambda_{i}^{t} !}}.\]

Therefore the joint posterior distribution of the model parameters 
given the observed data is:

\[P(\{p_{stay}\}, \gamma, {\langle R_{j}^{t}\rangle}_{j = 1, 2, \dots n}
   \mid 
   {\langle I_{j}^{t}\rangle)}_{j = 1, 2, \dots n} 
   \propto 
   \mathcal{L} \times 
   P\left(\langle R_{j}^{t}\rangle_{j = 1, 2, \dots n}\right) 
   P\left( p_{stay} \right) P\left( \gamma \right).\]

$P\left( p_{stay} \right)$,  $P\left( \gamma \right)$, and $P\left(\langle R_{j}^{t}\rangle_{j = 1, 2, \dots n}\right)$ 
represent the prior distributions on the parameters. 

Here, we have assumed a single $p_{stay}$ for all 
countries on African mainland. For estimating the time-varying
reproduction number for each country, we split the duration of the
total outbreak into intervals of equal width. We assume that
transmissibility in each location stays constant within each time 
window and thus,
within a time window, we estimated  a single reproduction number for
each location. We varied the length of this
time window to obtain different models, with short time windows 
increasing the number of parameters in the model. A comparison of the
different models is presented in Results 
(`r si_fig_nums("pm_model_perf_all_windows")`).

We assumed a Gamma distributed serial interval with mean 14.2 
days and standard deviation 9.6 days [@team2015west]. 
For the reproduction number, we used a Gamma prior with mean 
3.3 and variance 1.5. This was informed by a review of 
estimates of the reproduction number for Ebola Zaire in 
outbreaks preceding the West African Ebola outbreak which 
reported estimates ranging from 1.4 to 4.7 [@van2015review]. 
The mean prior 3.3 was chosen as the midpoint of this interval, 
and the variance 1.5, was chosen so the 95% prior probability
interval contains the extremes of this interval.

For the gravity model parameters $p_{stay}$ and $\gamma$, we 
chose uninformative uniform priors. 
Since $p_{stay}$ is a probability,
the prior was a uniform distribution on the interval $[0, 1]$.
For simplicity, and in the absence of 
data to inform these, 
we assumed the exponents $\alpha$ and $\beta$ on the
populations to be 1.
$\gamma$ was allowed to vary between 1 and 2 in the results presented
in the main text. We performed a sensitivity analysis where $\gamma$
has a uniform prior between 1 and 10. The results of this analysis are 
presented in the SI (`r section_nums("gamma_ul_section")`).

Model fitting was done in a Bayesian framework using a Markov Chain 
Monte Carlo (MCMC) approach as implemented in the software Stan [@carpenter2017stan] 
and its R interface rstan [@rstan]. Convergence of MCMC chains was 
confirmed using visual inspections of the diagnostics (Potential Scale
Reduction Factor [@gelman1992inference] 
and Geweke Diagnostics [@geweke]) reported by 
R package ggmcmc [@ggmcmc]. An example report produced by [@ggmcmc] is
included in the Supplementary Material.

For each model (i.e., for each choice of the time window), we made 
forward projections every 7\textsuperscript{th} day, over a 2 week, 
4 week and 6 week horizon. To forecast incidence from day $t$ onwards, 
we fitted the model to the daily incidence series up to day $t-1$.
We then sampled 1000 parameter sets (reproduction numbers for each 
location in each time window and parameters of the gravity model) 
from the joint posterior distribution, and for each parameter set, 
simulated one future epidemic trajectory 
according to equation (1), assuming that future $R_t$ is equal to the 
last estimated $R_t$ value in each location.
