---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
title: 
author:
- name: Sangeeta Bhatia
  affiliation: Imperial College London
abstract: 
keywords: 
date: "Y"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
bibliography: 
biblio-style: apsr
endnote: no
---


```{r setup}
library(dplyr)


```


# Wide Data load

Read in cleaned-up and wide formatted data. 

```{r hm_dataload, eval = TRUE}
hm_wide <- here::here("data/processed",
                      "healthmap_wide_from_july.csv") %>%
    readr::read_csv()

hm_wide$aggregated <- hm_wide$Guinea +
    hm_wide$Liberia +
    hm_wide$`Sierra Leone`

weekly_incid <- mRIIDS:::daily.to.weekly(hm_wide)

weekly_tall <- tidyr::gather(weekly_incid, country, incidence, -date)
weekly_tall$date <- as.Date(weekly_tall$date)
weekly_tall$week_starting <- lubridate::round_date(weekly_tall$date, "week")

```

## Read in projections

```{r}
twindow <- 49
t_proj <- seq(from = 98, to = 567, by = 7)
n.dates.sim <- 28
infiles <- paste("forecasts",
                 t_proj,
                 twindow,
                 n.dates.sim,
                 sep = "_")

infiles <- paste0(infiles, ".csv")
names(infiles) <- hm_wide$date[t_proj]
projections <- purrr::map_dfr(infiles,
                           ~ readr::read_csv(here::here("data/output",
                                                        .x)),
                           .id = "projection_from")
                           
```

Long to wide for y, ymin and ymax separately and then put them together.

```{r}
projections_y <- select(projections, - c(ymin, ymax))
projections_ymin <- select(projections, - c(y, ymax))
projections_ymax <- select(projections, - c(y, ymin))

projections_wide <- list(projections_y,
                         projections_ymin,
                         projections_ymax) %>%
    purrr::map(function(df) {
        df$date <- rep(1:4, nrow(df) / 4)
        df$countrydate <- paste(df$date, df$country, sep = ".")
        df <- select(df, - c(date, country))
        var <- colnames(select(df, - c(projection_from, countrydate)))
        df <- data.table::dcast(df, projection_from ~ countrydate, value.var = var)
        colnames(df)[-1] <- paste0(var, colnames(df[-1]))
        df
    })

projections_wide <- left_join(projections_wide[[1]],
                              projections_wide[[2]]) %>%
    left_join(projections_wide[[3]])


```


## Join to the incidence time series

```{r}

weekly_incid$date <- as.Date(weekly_incid$date)
projections_wide$projection_from <- as.Date(projections_wide$projection_from)
```
Tack on an additional column identifying week in both data sets.
```{r}
weekly_incid$week_starting <- lubridate::floor_date(weekly_incid$date,
                                                    unit = "week")

projections_wide$week_starting <- lubridate::floor_date(projections_wide$projection_from,
                                                        unit = "week")

```

```{r}
desired  <- dplyr::inner_join(weekly_incid,
                              projections_wide)
desired <- select(desired,
                  week_starting,
                  projection_from,
                  Liberia:`ymax4.Sierra Leone`,
                  -one_of("date"))
                  

```
