---
output: 
pdf_document:
citation_package: natbib
keep_tex: false
fig_caption: true
latex_engine: pdflatex
title: Visualization of forecasts
author:
- name: Sangeeta Bhatia
affiliation: Imperial College London
abstract: 
keywords: 
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: 
biblio-style: apsr
endnote: no
params:
  tproj : !r seq(from = 84, by = 28, to = 300)
  twindow : 42
  incid : healthmap_wide_from_july.csv
  n.dates.sim : 28
  place: Liberia
---

```{r setup, eval = TRUE}
library(dplyr)
library(purrr)
library(ggplot2)
library(RColorBrewer)
```
First define the color pallete to be used throughout.

```{r}
mypalette <- brewer.pal(length(params$tproj), "Dark2")
```

Read in the projections output.

```{r forecasts}
infiles <- paste0("forecasts_",
                    params$tproj,
                    "_",
                    params$twindow,
                    "_",
                    params$n.dates.sim,
                    ".csv")
names(infiles) <- paste0(params$tproj,
                           "_",
                           params$twindow,
                           "_",
                           params$n.dates.sim
                           )
forecasts <- map_dfr(infiles, ~ readr::read_csv(here::here("data/output",
                                                             .x)),
                     .id = "parameters") %>%
    filter(country == params$place)


```

Read in R estimates.

```{r restim}

infiles <- here::here("data/stanfits",
                      paste0(params$place,
                             "_rquantiles_",
                             params$tproj,
                             "_",
                             params$twindow,
                             ".rds"))

names(infiles) <-  paste0(params$tproj,
                          "_",
                          params$twindow)
                          

restim <- map_dfr(infiles, readRDS, .id = "parameters")
```

Read in the incidence. Chop it off at a little more than the max of 
the times at which we are projecting.

```{r incid}
cutoff <- max(params$tproj) + (2 * params$n.dates.sim)
incid <- incid <- here::here("data/processed",
                    params$incid) %>%
    readr::read_csv(n_max = cutoff) %>%
    select(date, params$place) %>%
    mRIIDS:::daily.to.weekly(.)

incid <- rename(incid,
                "incidence" = params$place)

incid$date <- as.Date(incid$date)
```

Finally plot everything.

```{r forecastsplot}
p <- ggplot()
p <- p + geom_point(data = incid,
                    aes(date, incidence),
                    col = "blue")
## plot projections on top
p <- p + geom_ribbon(data = forecasts,
                     aes(x = date,
                         ymin = ymin,
                         ymax = ymax,
                         fill = parameters),
                     alpha = 0.3)
p <- p + geom_line(data = forecasts,
                     aes(x = date,
                         y = y,
                         col = parameters))

p <-  p + theme_classic()
p <- p + xlab("") + ylab("Weekly Incidence")

```
Also highlight the part of the incidence curve used to estimate the R
used.

```{r}
used_from <- incid$date[(params$tproj - params$twindow) / 7]
used_to <- incid$date[(params$tproj) / 7]
p <- p + geom_vline(xintercept = as.numeric(c(used_from, used_to)),
                    linetype = "dotted")

```

Plot 2. 

```{r rplot}
p2 <- ggplot()
p2 <- p2 + geom_line(data = restim,
                     aes(x = date,
                         y = `50%`,
                         col = parameters))

p2 <- p2 + geom_ribbon(data = restim,
                       aes(x = date,
                           ymin = `2.5%`,
                           ymax = `97.5%`,
                           fill = parameters),
                       alpha = 0.3)
p2 <- p2 + theme_classic()
p2 <- p2 + xlab("") + ylab("R")
```

Finally, write it out with a common legend.

```{r save}
prefix <- paste0(params$tproj,
                 collapse = "_")
outfile <- here::here("data/output/figures",
                      paste0(params$place,
                             "_",
                             prefix,
                             "_",
                             params$twindow,
                             "_",
                             params$n.dates.sim,
                             ".png"))
ggpubr::ggarrange(p,
                  p2,
                  ncol = 1,
                  nrow = 2,
                  common.legend = TRUE,
                  legend="bottom") %>%
    ggpubr::ggexport(filename = outfile)
```
