---
output: 
pdf_document:
citation_package: natbib
keep_tex: false
fig_caption: true
latex_engine: pdflatex
title: Visualisation of weekly performance metrics
author:
- name: Sangeeta Bhatia
affiliation: Imperial College London
abstract: 
keywords: 
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: 
biblio-style: apsr
endnote: no
params:
  twindow : 14
  n.dates.sim : 28
  places: !r c("SLE", "LBR", "GIN")
  indir: data/healthmap_gamma_ul_10_output
  outdir: data/healthmap_gamma_ul_10_output/
  datasource: HealthMap
---

```{r setup, eval = TRUE}
library(dplyr)
library(purrr)
library(ggplot2)
source(here::here("analysis/common_plot_properties.R"))
```



```{r forecasts-assess-viz-1 }
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  dev = "png",
  ## fig.width = 7,
  ## dev.args = list(pointsize = 6),
  fig.path = here::here(params$outdir),
  fig.ext = paste0(
    params$datasource,
    "_",
    params$twindow,
    "_",
    params$n.dates.sim,
    "_assess.png"
  )
)
```
Read in the files for all places of interest and visualise.

```{r forecasts-assess-viz-2 }

weekly_metrics <- readr::read_csv(
  file = here::here(
    params$indir,
    "weekly_metrics.csv"
  )
)
```

Join it with R estimate categorisation.

```{r forecasts-assess-viz-3 }

epidemic_phase <- readr::read_csv(
  file = here::here(
    params$outdir,               
    paste0(
      params$datasource,
      "_rquantiles_projection.csv"
    )
  )
)

epidemic_phase <- epidemic_phase[
  epidemic_phase$twindow == params$twindow,
]

epidemic_phase <- epidemic_phase[rep(
    seq_len(nrow(epidemic_phase)),
    each = params$n.dates.sim), ]

## Fix the dates.
epidemic_phase <- dplyr::group_by(
    epidemic_phase,
    tproj,
    country
    ) %>%
    dplyr::mutate(
    date = seq(from = min(date), length.out = params$n.dates.sim, by = "1 day")
)



weekly_metrics <- dplyr::left_join(
  weekly_metrics,
  epidemic_phase,
  by = c("tproj", "twindow", "country")
)

weekly_metrics <- weekly_metrics[
  weekly_metrics$twindow == params$twindow &
    weekly_metrics$n.dates.sim == params$n.dates.sim,
]
```

## Fix column classes
```{r forecasts-assess-viz-4 }

weekly_metrics <- dplyr::mutate_if(
  weekly_metrics,
  is.character,
  factor
)
weekly_metrics$week_of_projection <- factor(weekly_metrics$week_of_projection)

weekly_metrics$ci <- forcats::fct_recode(
  weekly_metrics$ci,
  "Neither" = "ci_includes_1",
  "Growing" = "ll_greater_than_1",
  "Declining" = "ul_less_than_1"
)
weekly_metrics$tproj <- as.integer(weekly_metrics$tproj)
weekly_metrics$twindow <- factor(weekly_metrics$twindow)
```

```{r forecasts-assess-viz-5 }

summary_stats <- summarise_at(
  weekly_metrics,
  vars(rmae:logaccuracy),
  list(
    med = ~ quantile(., 0.5, na.rm = TRUE),
    low = ~ quantile(., 0.25, na.rm = TRUE),
    high = ~ quantile(., 0.75, na.rm = TRUE)
  )
)

summary_stats <- tidyr::gather(
  summary_stats,
  key = metric,
  value = value
) %>%
  tidyr::separate(
    col = metric,
    into = c("metric", "bound")
  ) %>%
  tidyr::spread(
    key = bound,
    value = value,
    convert = TRUE
  )

select(
  summary_stats,
  metric,
  med,
  low,
  high
) %>% knitr::kable()
```

## Summary stats by week


```{r forecasts-assess-viz-6 }

weekly_summary_stats <- group_by(weekly_metrics, week_of_projection) %>%
  summarise_at(
    vars(rmae:logaccuracy),
    list(
      med = ~ quantile(., 0.5, na.rm = TRUE),
      low = ~ quantile(., 0.25, na.rm = TRUE),
      high = ~ quantile(., 0.75, na.rm = TRUE)
    )
  )

weekly_summary_stats <- tidyr::gather(
  weekly_summary_stats,
  key = metric,
  value = value,
  -week_of_projection
) %>%
  tidyr::separate(
    col = metric,
    into = c("metric", "bound")
  ) %>%
  tidyr::spread(
    key = bound,
    value = value,
    convert = TRUE
  )

weekly_summary_stats <- dplyr::mutate_if(
  weekly_summary_stats,
  is.numeric,
  round,
  3
)

weekly_summary_stats$formatted_iqr <- paste0(
  weekly_summary_stats$med,
  " (",
  weekly_summary_stats$low,
  " - ",
  weekly_summary_stats$high,
  ")"
)

weekly_summary_stats <- dplyr::select(
  weekly_summary_stats,
  week_of_projection,
  metric,
  formatted_iqr
) %>%
  tidyr::spread(
    key = metric,
    value = formatted_iqr
  )
```

```{r forecasts-assess-viz-7}
knitr::kable(weekly_summary_stats)
```

## Summary stats by week and phase of epidemic
```{r forecasts-assess-viz-8}
phase_weekly_summary_stats <- group_by(
  weekly_metrics,
  week_of_projection,
  ci
) %>%
  summarise_at(
    vars(rmae:logaccuracy),
    list(
      med = ~ quantile(., 0.5, na.rm = TRUE),
      low = ~ quantile(., 0.25, na.rm = TRUE),
      high = ~ quantile(., 0.75, na.rm = TRUE)
    )
  )

phase_weekly_summary_stats <- tidyr::gather(
  phase_weekly_summary_stats,
  key = metric,
  value = value,
  -week_of_projection,
  -ci
) %>%
  tidyr::separate(
    col = metric,
    into = c("metric", "bound")
  ) %>%
  tidyr::spread(
    key = bound,
    value = value,
    convert = TRUE
  )

phase_weekly_summary_stats <- dplyr::mutate_if(
  phase_weekly_summary_stats,
  is.numeric,
  round,
  3
)

phase_weekly_summary_stats$formatted_iqr <- paste0(
  phase_weekly_summary_stats$med,
  " (",
  phase_weekly_summary_stats$low,
  " - ",
  phase_weekly_summary_stats$high,
  ")"
)

phase_weekly_summary_stats <- dplyr::select(
  phase_weekly_summary_stats,
  week_of_projection,
  ci,
  metric,
  formatted_iqr
) %>%
  tidyr::spread(
    key = metric,
    value = formatted_iqr
  )
```

```{r forecasts-assess-viz-9}
knitr::kable(phase_weekly_summary_stats)
```
## Bias

```{r forecasts-assess-viz-10 }
pbias <- ggplot(
  weekly_metrics,
  aes(week_of_projection,
    bias,
    col = ci
  )
) +
  geom_boxplot(position = "dodge")
pbias <- pbias +
  xlab("Week of projection") +
  ylab("Bias") +
  mriids_plot_theme$theme +
  mriids_plot_theme$legend

pbias
```

## Sharpness


```{r forecasts-assess-viz-11 }
psharp <- ggplot(
  weekly_metrics,
  aes(week_of_projection,
    sharpness,
    col = ci
  )
) +
  geom_boxplot()

psharp <- psharp +
  xlab("Week of projection") +
  ylab("Sharpness") +
  mriids_plot_theme$theme +
  mriids_plot_theme$legend

psharp
```

## Relative accuracy


```{r forecasts-assess-viz-12 }
prel <- ggplot(
  weekly_metrics,
  aes(week_of_projection,
    logaccuracy,
    col = ci
  )
) +
  geom_boxplot()
## geom_point(aes(fill = ci),
##            alpha = 0.7,
##            position = position_jitterdodge())
prel <- prel +
  xlab("Week of projection") +
  ylab("log relative accuracy") +
  mriids_plot_theme$theme +
  mriids_plot_theme$legend

prel
```


## Relative mean absolute error


```{r forecasts-assess-viz-13 }
prelerr <- ggplot(
  weekly_metrics,
  aes(week_of_projection,
    rmae,
    col = ci
  )
) +
  geom_boxplot()

prelerr <- prelerr +
  mriids_plot_theme$theme +
  mriids_plot_theme$legend


prelerr <- prelerr +
  xlab("Week of projection") +
  ylab("Relative mean absolute error")

prelerr
```


```{r forecasts-assess-viz-14 }
outfile <- here::here(
  params$outdir,
  paste0(
    "forecasts_assess_",
    params$datasource,
    params$twindow,
    ".png"
  )
)

## Affix legend manually otherwise I can't get rid of the
## annoying legend title.
legend <- cowplot::get_legend(pbias +
  theme(
    legend.position = "bottom",
    legend.title = element_blank()
  ))

prow <- cowplot::plot_grid(pbias + theme(legend.position = "none"),
  psharp + theme(legend.position = "none"),
  prel + theme(legend.position = "none"),
  prelerr + theme(legend.position = "none"),
  align = "vh",
  labels = c("A", "B", "C", "D"),
  hjust = -1,
  nrow = 2
)


# add the legend underneath the row we made earlier. Give it 10% of the height
# of one plot (via rel_heights).
p <- cowplot::plot_grid(prow,
  legend,
  ncol = 1,
  rel_heights = c(1, .1)
)

p
```
