---
output: 
pdf_document:
citation_package: natbib
keep_tex: false
fig_caption: true
latex_engine: pdflatex
title: Model performance metrics stratified by datasource
author:
- name: Sangeeta Bhatia
affiliation: Imperial College London
abstract: 
keywords: 
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: 
biblio-style: apsr
endnote: no
params:
  datasources: !r c("ProMED", "HealthMap", "WHO")
  indirs: !r c("data/output", "data/healthmap_output", "data/who_output")
  twindow: 14
  n.dates.sim: 28
---

```{r setup, eval = TRUE}
library(dplyr)
library(purrr)
library(ggplot2)
source(here::here("analysis/common_plot_properties.R"))

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  dev = "pdf",
  fig.ext = glue::glue("{params$twindow}_{params$n.dates.sim}.pdf"),
  fig.path = here::here(glue::glue("ms-figures/si-figures/other/{Sys.Date()}/")),
  fig.width = mriids_plot_theme$single_col_width / 2.5,
  fig.height = mriids_plot_theme$single_col_height / 2.5
  )

```

Read in metrics for each datasource.

```{r forecasts-assess-by-datasource-1 }
infiles <- glue::glue("{params$indirs}/{params$datasources}_weekly_metrics.csv")
names(infiles) <- {
  params$datasources
}
weekly_metrics <- purrr::map_dfr(infiles, ~ readr::read_csv(
  file = here::here(.x)
),
.id = "datasource"
)

weekly_metrics <- dplyr::filter(
  weekly_metrics,
  twindow == params$twindow,
  n.dates.sim == params$n.dates.sim
  )
weekly_metrics <-  dplyr::rename(weekly_metrics, relsharpness = "rel_sness")
weekly_metrics$week_of_projection <- factor(weekly_metrics$week_of_projection)
weekly_metrics <- dplyr::mutate_if(weekly_metrics, is.character, factor)
weekly_metrics <- dplyr::mutate_at(weekly_metrics, vars(tproj, twindow, n.dates.sim), as.integer)
```

## Bias

```{r forecasts-assess-by-datasource-2 }
pbias <- ggplot(
  weekly_metrics,
  aes(week_of_projection,
    bias,
    col = datasource
  )
) +
  geom_boxplot(position = "dodge", outlier.size = 1, outlier.stroke = 0.1)

pbias <- pbias +
  xlab("") +
  ylab("bias") +
  mriids_plot_theme$onecol_theme +
  mriids_plot_theme$legend +
  scale_color_manual(values = mriids_plot_theme$color_scale)

pbias
```

## Relative Sharpness


```{r forecasts-assess-by-datasource-3 }

psharp <- ggplot(
  weekly_metrics,
  aes(week_of_projection,
    relsharpness,
    col = datasource
  )
) +
  geom_boxplot(outlier.size = 1, outlier.stroke = 0.1)
## scale_y_log10(
##   breaks = scales::trans_breaks("log10", function(x) 10^x),
##   labels = scales::trans_format("log10", scales::math_format(10^.x))
## )


psharp <- psharp +
  xlab("") +
  ylab("sharpness") +
  mriids_plot_theme$onecol_theme +
  mriids_plot_theme$legend +
  scale_color_manual(values = mriids_plot_theme$color_scale)

psharp
```

## Proportion of observations in CrI


```{r forecasts-assess-by-datasource-4 }
propinci_perc <- group_by(
  weekly_metrics,
  week_of_projection,
  datasource
) %>% summarise(nweeks = 100 * sum(propinci) / n())
propinci_perc <- dplyr::ungroup(propinci_perc)
prel <- ggplot(
  propinci_perc,
  aes(week_of_projection,
    nweeks,
    fill = datasource
  )
) +
  geom_bar(stat = "identity", position = "dodge", width = 0.5)
## geom_point(aes(fill = ci),
##            alpha = 0.7,
##            position = position_jitterdodge())
prel <- prel +
  xlab("") +
    ylab(
        stringr::str_wrap("% weeks in 95% forecast interval", width = 15)
    ) +
  mriids_plot_theme$onecol_theme +
  mriids_plot_theme$legend +
  ylim(0, 100) +
  scale_fill_manual(values = mriids_plot_theme$color_scale)

prel
```


## Relative mean absolute error


```{r forecasts-assess-by-datasource-5 }
prelerr <- ggplot(
  weekly_metrics,
  aes(week_of_projection,
    rmae,
    col = datasource
  )
) +
    geom_boxplot(outlier.size = 1, outlier.stroke = 0.1) 

prelerr <- prelerr +
  mriids_plot_theme$onecol_theme +
  mriids_plot_theme$legend +
  scale_color_manual(values = mriids_plot_theme$color_scale)


prelerr <- prelerr +
  xlab("") +
  ylab("relative mean absolute error")

prelerr
```

```{r forecasts-assess-by-datasource-6}
prelerr_log <- prelerr +
      scale_y_log10(
    breaks = scales::trans_breaks(trans = "log10", inv = function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(.x))) +
     ylab("log(rmae)") +   theme(
        axis.title = ggplot2::element_text(margin = margin(t = 0, r = 0, b = 0, l = 0), size = 6)
    ) 
```

```{r forecasts-assess-by-datasource-7 }
## outfile <- here::here(
##   params$outdir,
##   paste0(
##     "forecasts_assess_",
##     params$datasource,
##     params$twindow,
##     ".pdf"
##   )
## )

## Affix legend manually otherwise I can't get rid of the
## annoying legend title.
legend <- cowplot::get_legend(pbias +
  theme(
    legend.position = "bottom",
    legend.title = element_blank()
  ))

prow <- cowplot::plot_grid(
  prel + theme(legend.position = "none"),
  prelerr + theme(legend.position = "none"),
  pbias + theme(legend.position = "none"),
  psharp + theme(legend.position = "none"),
  align = "vh",
  labels = c("A", "B", "C", "D"),
  label_size = 8,
  hjust = c(-1, 1, -3, 1),
  vjust = c(3, 3, -2.5, 0),
  nrow = 2
)



# add the legend underneath the row we made earlier. Give it 10% of the height
# of one plot (via rel_heights).
p <- cowplot::plot_grid(prow,
  legend,
  ncol = 1,
  rel_heights = c(1, .1)
) 

p
```

And with log scale.

```{r forecasts-assess-by-datasource-8 }
prow <- cowplot::plot_grid(
  prel + theme(legend.position = "none"),
  prelerr_log + theme(legend.position = "none"),
  pbias + theme(legend.position = "none"),
  psharp + theme(legend.position = "none"),
  align = "vh",
  labels = c("A", "B", "C", "D"),
  label_size = 8,
  hjust = c(-1, 1, -3, 1),
  vjust = c(3, 3, -2.5, 0),
  nrow = 2
)


# add the legend underneath the row we made earlier. Give it 10% of the height
# of one plot (via rel_heights).
p <- cowplot::plot_grid(prow,
  legend,
  ncol = 1,
  rel_heights = c(1, .1)
)

p
```
