---
output: 
pdf_document:
citation_package: natbib
keep_tex: false
fig_caption: true
latex_engine: pdflatex
title: Visualization of forecasts
author:
- name: Sangeeta Bhatia
affiliation: Imperial College London
abstract: 
keywords: 
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: 
biblio-style: apsr
endnote: no
params:
  twindow : 14
  incid : data/processed/16042019_healthmap_loglinear_weekly.csv
  n.dates.sim : 28
  places: !r c("LBR", "SLE", "GIN")
  outdir: data/healthmap_gamma_ul_10_output
  datasource: HealthMap
---

```{r projections-viz-fixed-country-2 }
source(here::here("analysis/common_plot_properties.R"))
```

```{r projections-viz-fixed-country-1, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  dev = "pdf",
  fig.width = mriids_plot_theme$double_col_width / 2.5,
  fig.asp = 1/1.6,
  fig.path = here::here(paste0(params$outdir, "/")),
  fig.ext = paste0(
    params$datasource,
    "_",
    params$twindow,
    "_",
    params$n.dates.sim,
    ".pdf"
  )
)
```

```{r setup, eval = TRUE}
library(dplyr)
library(purrr)
library(ggplot2)
library(scales)
library(patchwork)
```

## Real-time R estimates

Read in R estimates.

```{r projections-viz-fixed-country-3, eval = TRUE}

rused <- readr::read_csv(
  file = here::here(
    params$outdir,
    paste0(
      params$datasource,
      "_rquantiles_projection.csv"
    )
  )
)

rused$tproj <- as.integer(rused$tproj)
rused$twindow <- as.integer(rused$twindow)
rused <- rused[rused$twindow == params$twindow, ]

rused <- rused[rep(
    seq_len(nrow(rused)),
    each = params$n.dates.sim), ]

## Fix the dates.
rused <- dplyr::group_by(
    rused,
    tproj,
    country
    ) %>%
    dplyr::mutate(
    date = seq(from = min(date), length.out = params$n.dates.sim, by = "1 day")
)





rused$country <- forcats::fct_recode(rused$country,
  Guinea = "GIN",
  Liberia = "LBR",
  `Sierra Leone` = "SLE"
)
rused$rcategory <- "R[t - 1]"
```

```{r projections-viz-fixed-country-4}
rretro <- readr::read_csv(
  file = here::here(
    params$outdir,
    paste0(
      params$datasource,
      "_rquantiles_retrospective.csv"
    )
  )
)

rretro$country <- forcats::fct_recode(rretro$country,
  Guinea = "GIN",
  Liberia = "LBR",
  `Sierra Leone` = "SLE"
)
rretro$rcategory <- "R[retrospective]"
rretro <- rretro[rretro$twindow == params$twindow, ]
rused <- rused[, colnames(rretro)]

```
## Observed and projected incidence




Read in the weekly incidence in tall form. 

```{r projections-viz-fixed-country-5 }

incid <- here::here(params$incid) %>%
  readr::read_csv() %>%
  filter(country %in% params$places)

incid <- filter(
  incid,
  date <= max(rused$date) + 14
)
```

Read in the projections output.

```{r projections-viz-fixed-country-6 }

forecasts <- readr::read_csv(
  file = here::here(
    params$outdir,
    "all_forecasts_quantiles_consolidated.csv"
  )
)
forecasts$tproj <- as.integer(forecasts$tproj)
forecasts$time_window <- as.integer(forecasts$time_window)

forecasts <- filter(
  forecasts,
  country %in% params$places &
  time_window == params$twindow &
  n.dates.sim == params$n.dates.sim
)

```
Relabel factors to get nice facet labels.

```{r projections-viz-fixed-country-7 }

incid$country <- forcats::fct_recode(incid$country,
  Guinea = "GIN",
  Liberia = "LBR",
  `Sierra Leone` = "SLE"
)


forecasts$country <- forcats::fct_recode(forecasts$country,
  Guinea = "GIN",
  Liberia = "LBR",
  `Sierra Leone` = "SLE"
)
```

Since we are going to take logs, maybe add 1 to everything.
```{r projections-viz-fixed-country-8 }

incid$incid <- incid$incid + 1
forecasts <- dplyr::mutate_at(
  forecasts,
  vars(`0%`:`100%`),
  ~ .x + 1
)
incid$source <- params$datasource
```

```{r projections-viz-fixed-country-9}

non_overlapping <- seq(
  from = min(forecasts$tproj),
  to = max(forecasts$tproj),
  by = params$n.dates.sim
)

forecasts <- dplyr::filter(
  forecasts,
  tproj %in% non_overlapping
  )

```

```{r}
rused <- dplyr::ungroup(rused)
rused <- dplyr::filter(
    rused,
    tproj %in% non_overlapping
)
rboth <- rbind(rused, rretro)
```

```{r projections-viz-fixed-country-10 }
rretro_lims <- dplyr::group_by(
  rboth,
  country
) %>%
  dplyr::summarise(
    ylow = floor(min(`2.5%`)),
    yhigh = ceiling(max(`97.5%`))
  )
rreal_lims <- dplyr::group_by(
  rboth,
  country
) %>%
  dplyr::summarise(
    ylow = floor(min(`2.5%`)),
    yhigh = ceiling(max(`97.5%`))
  )
```

Finally plot everything.

```{r projections-viz-fixed-country-11 }
p <- ggplot()
p <- p + geom_point(
  data = incid,
  aes(date,
    incid,
    col = interaction(
      source,
      interpolated
    )
    ),
   shape = 20     
)

p <- p + geom_ribbon(
  data = forecasts,
  aes(
    x = date,
    ymin = `2.5%`,
    ymax = `97.5%`,
    group = tproj
  ),
  fill = "gray45",
  alpha = 0.3
)

p <- p + geom_line(
  data = forecasts,
  aes(
    x = date,
    y = `50%`,
    group = tproj
  ),
  col = "gray3"
)


p <- p + scale_y_continuous(trans = "log10")

p <- p +
  xlab("") +
  ylab("log(weekly incidence)")

## p <- p +
##   scale_x_date(
##     date_breaks = "3 month",
##     labels = date_format("%b %Y")
##   ) +
##   theme(axis.text.x = element_text(angle = 90, hjust = 0))

p <- p +
    scale_x_date(labels = mriids_plot_theme$dateformat) +
    mriids_plot_theme$xticklabels

p <- p + facet_wrap(~country, nrow = 1, scales = "fixed")
p <- p +
  scale_colour_manual(values = mriids_plot_theme$color_scale) +
  mriids_plot_theme$theme +
  mriids_plot_theme$legend

p
```



```{r projections-viz-fixed-country-12, eval = TRUE}
pretro <- ggplot() +
  expand_limits(x = min(incid$date))
pretro <- pretro + geom_line(
  data = rretro,
  aes(
    x = date,
    y = `50%`
  ),
  col = "gray"
)
pretro <- pretro + geom_ribbon(
  data = rretro,
  aes(
    x = date,
    ymin = `2.5%`,
    ymax = `97.5%`
  ),
  alpha = 0.3
)
pretro <- pretro + geom_hline(
  yintercept = 1,
  linetype = "dashed",
  col = "red"
)

pretro <- pretro + xlab("") + ylab(expression(R[retrospective]))
pretro <- pretro + scale_x_date(labels = mriids_plot_theme$dateformat)
  ## scale_x_date(
  ##   date_breaks = "3 month",
  ##   labels = date_format("%b %Y")
  ## )
## pretro <- pretro +
##   theme(axis.text.x = element_text(angle = 90, hjust = 0))

pretro <- pretro +
  facet_wrap(~country, nrow = 1, scales = "free_y")
pretro <- pretro +
  geom_blank(data = rretro_lims)

pretro <- pretro +
  scale_colour_manual(values = mriids_plot_theme$color_scale) +
  mriids_plot_theme$theme +
  mriids_plot_theme$legend

pretro
```



```{r projections-viz-fixed-country-13, eval = TRUE}

preal <- ggplot()
preal <- preal + expand_limits(x = min(incid$date))
preal <- preal +
  geom_blank(data = rreal_lims)
preal <- preal + geom_line(
  data = rused,
  aes(
    x = date,
    y = `50%`,
    group = tproj
  ),
  ## group = parameters),
  col = "gray"
)
preal <- preal + geom_ribbon(
  data = rused,
  aes(
    x = date,
    ymin = `2.5%`,
    ymax = `97.5%`,
    group = tproj
  ),
  alpha = 0.3
)
preal <- preal + geom_hline(
  yintercept = 1,
  linetype = "dashed",
  col = "red"
)

preal <- preal + xlab("") + ylab(expression(R[t - 1]))
preal <- preal + scale_x_date(labels = mriids_plot_theme$dateformat)
  ## scale_x_date(
  ##   date_breaks = "3 month",
  ##   labels = date_format("%b %Y")
  ## )
## Force x-axis to begin from the time we have incidence date
## so that maps are better aligned.


preal <- preal +
  facet_wrap(~country, nrow = 1, scales = "free_y")

preal <- preal +
  scale_colour_manual(values = mriids_plot_theme$color_scale) +
  mriids_plot_theme$theme +
  mriids_plot_theme$legend

preal
##    theme(axis.text.x = element_text(angle = 90, hjust = 0))
```




```{r projections-viz-fixed-country-14 }

rboth$rcategory <- factor(rboth$rcategory,
  levels = c(
    "R[t - 1]",
    "R[retrospective]"
  )
)

pboth <- ggplot(rboth) +
  geom_line(aes(date, `50%`)) +
  facet_grid(rcategory ~ country,
    scales = "free_y",
    switch = "y",
    labeller = label_parsed
  ) +
  mriids_plot_theme$theme +
  mriids_plot_theme$legend +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    panel.spacing = unit(2, "lines"),
    strip.placement = "outside"
  ) +
  ylab(NULL)



pboth <- pboth + geom_ribbon(
  aes(
    x = date,
    ymin = `2.5%`,
    ymax = `97.5%`

  ),
  alpha = 0.3
)
pboth <- pboth + geom_hline(
  yintercept = 1,
  linetype = "dashed",
  col = "red"
)

pboth <- pboth + xlab("") + ylab("")
pboth <- pboth + scale_x_date(labels = mriids_plot_theme$dateformat)
pboth <- pboth + mriids_plot_theme$xticklabels     

pboth
```






```{r projections-viz-fixed-country-15 }

p2 <- p +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.line.x = element_blank()
  )


pall <- cowplot::plot_grid(p2, pboth, nrow = 2, rel_heights = c(0.7, 1), align = "hv", axis="l")


pall
```

```{r projections-viz-fixed-country-16 }
pall2 <- p +
  preal +
  pretro +
  plot_layout(nrow = 3, heights = c(2, 1, 1)) 
##  theme(axis.text.x = element_text(angle = 90, hjust = 0))

pall2
```


