---
output: 
pdf_document:
citation_package: natbib
keep_tex: false
fig_caption: true
latex_engine: pdflatex
title: Consolidate forecasts performance metrics
author:
- name: Sangeeta Bhatia
affiliation: Imperial College London
abstract: 
keywords: 
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: 
biblio-style: apsr
endnote: no
params:
  twindow : 14
  tproj : !r seq(from = 49, to = 614, by = 7)
  n.dates.sim : 28
  place: SLE
  indir: data/who_output/metrics/weekly
  outdir: data/who_output/metrics/weekly
---

```{r setup, eval = TRUE}
library(dplyr)
library(purrr)
library(ggplot2)
```
Read in the weekly metrics for given parameters.

```{r metrics}
infiles <- paste0(params$place,
                  "_weekly_metrics_",
                  params$tproj,
                  "_",
                  params$twindow,
                  "_",
                  params$n.dates.sim,
                  ".csv")
names(infiles) <- paste0(params$tproj,
                         "_",
                         params$twindow,
                         "_",
                         params$n.dates.sim
                         )
metrics <- map_dfr(infiles,
                   ~ readr::read_csv(here::here(params$indir,
                                                .x)),
                     .id = "parameters") 


```

Add a week column.

```{r}
metrics <- tidyr::separate(metrics,
                           parameters,
                           into = c("tproj", "twindow", "ndates"),
                           sep = "_",
                           remove = TRUE,
                           convert = TRUE
                           )

metrics <- dplyr::arrange(metrics, tproj)
num_weeks <- params$n.dates.sim / 7
metrics$week_of_projection <- rep(1:num_weeks,
                                  ceiling(nrow(metrics) / num_weeks))[seq_len(nrow(metrics))]

metrics <- mutate_if(metrics, is.character, factor)
metrics$country <- params$place

```

Write out the metrics for further 

```{r}
outfile <- paste0(params$place,
                  "_weekly_",
                  params$twindow,
                  "_",
                  params$n.dates.sim,
                  ".csv")

readr::write_csv(x = metrics,
                 path = here::here(params$outdir,
                                   outfile))
```
