---
output: 
pdf_document:
citation_package: natbib
keep_tex: false
fig_caption: true
latex_engine: pdflatex
title: Pre-processing ProMED feed
author:
- name: Sangeeta Bhatia
affiliation: Imperial College London
abstract: 
keywords: 
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: 
biblio-style: apsr
endnote: no
---

The column names are different from the column names in Healthmap
feed. Once the columns have been renamed, the rest of the processing
is the same as that for healthmap feed.

# Rename columns

```{r pmread, echo=FALSE}
library(dplyr)
library(lubridate)
promed <- here::here("data/raw",
                     "ProMED_Ebola_2014-2016.csv") %>%
    readr::read_csv()
```



```{r hmread, echo = FALSE}

promed <- rename(promed,
                 "SC" = "Cumulative SC",
                 "SD" = "Cumulative SD",
                 "CC" = "Cumulative CC",
                 "CD" = "Cumulative CD",
                 "URL" = "Headline",
                 "HealthMap Alert ID" = "HM Alert ID")
```
And force the promed date format into one consistent with healthmap
date format.

```{r}
promed$`Issue Date` <- lubridate::dmy_hm(promed$`Issue Date`)
promed$`Issue Date` <- paste0(month(promed$`Issue Date`),
                              "/", day(promed$`Issue Date`),
                              "/", substring(year(promed$`Issue Date`),
                                             3,
                                             4),
                              " ", hour(promed$`Issue Date`),
                              ":", minute(promed$`Issue Date`))
```

```{r}
readr::write_csv(x = promed,
                 path = here::here("data/raw",
                                   "promed_2014-2016-renamed.csv"))
```
